export const contractAddress = "0x861ACCC81DE9A158c5a0660b344870E8D4a3A11A";
export const API = "https://protocol-sandbox.lumx.io/v2";

export const shipsData = [
  {
    id: 0,
    title: "Zephyr - 7",
    subtitle: "STANDARD SHIP",
    multiplier: 1,
    description:
      "ZEPHYR - 7 is the perfect choice for beginner pilots. Equipped with precise and consistent shots, it is ideal for those starting their space journey.",
    shots: 1,
    hp: 100,
    cooldown: 6,
    price: 0.1,
    shipImg: "/images/nave1.png",
    shipGameImg: "/gameImages/nave1.png",
  },
  {
    id: 1,
    title: "TITAN STEEL",
    subtitle: "HEAVY SHIP",
    multiplier: 2,
    description:
      "TITAN STEEL is a robust and powerful ship with high-density shots that ensure greater impact. Perfect for facing more resilient enemies.",
    shots: 2,
    hp: 150,
    cooldown: 4,
    price: 0.2,
    shipImg: "/images/nave2.png",
    shipGameImg: "/gameImages/nave2.png",
  },
  {
    id: 2,
    title: "TECH VIPER",
    subtitle: "FAST SHIP",
    multiplier: 3,
    description:
      "TECH VIPER is known for its speed and agility. Its rapid and precise shots make it a formidable opponent on the battlefield.",
    shots: 3,
    hp: 200,
    cooldown: 2,
    price: 0.3,
    shipImg: "/images/nave3.png",
    shipGameImg: "/gameImages/nave3.png",
  },
  {
    id: 3,
    title: "ARK4NGEL",
    subtitle: "INFERNO SHIP",
    multiplier: 4,
    description:
      "ARK4NGEL is the ship for true masters. With devastating whip-shaped shots, it can easily dominate any opponent.",
    shots: 50,
    hp: 250,
    cooldown: 0.5,
    price: 0.4,
    shipImg: "/images/nave4.png",
    shipGameImg: "/gameImages/nave4.png",
  },
];

export const playersData = [
  {
    playerAddress: "0x00...0000",
    status: "lost",
    result: "0",
    ship_class: "ZEPHYR-7",
    current_score: "10",
    challenge_time: "12",
    bet_amount: "31.00",
  },
  {
    playerAddress: "0x00...0000",
    status: "won",
    result: "50",
    ship_class: "TITAN STEEL",
    current_score: "60",
    challenge_time: "48",
    bet_amount: "31.20",
  },
  {
    playerAddress: "0x00...0000",
    status: "won",
    result: "50",
    ship_class: "ZEPHYR-7",
    current_score: "10",
    challenge_time: "12",
    bet_amount: "50.66",
  },
  {
    playerAddress: "0x00...0000",
    status: "won",
    result: "0",
    ship_class: "TITAN STEEL",
    current_score: "60",
    challenge_time: "48",
    bet_amount: "31.20",
  },
  {
    playerAddress: "0x00...0000",
    status: "won",
    result: "50",
    ship_class: "ZEPHYR-7",
    current_score: "10",
    challenge_time: "12",
    bet_amount: "50.66",
  },
  {
    playerAddress: "0x00...0000",
    status: "won",
    result: "50",
    ship_class: "TITAN STEEL",
    current_score: "60",
    challenge_time: "48",
    bet_amount: "31.20",
  },
  {
    playerAddress: "0x00...0000",
    status: "won",
    result: "50",
    ship_class: "ZEPHYR-7",
    current_score: "10",
    challenge_time: "12",
    bet_amount: "50.66",
  },
  {
    playerAddress: "0x00...0000",
    status: "won",
    result: "50",
    ship_class: "TITAN STEEL",
    current_score: "60",
    challenge_time: "48",
    bet_amount: "31.20",
  },
  {
    playerAddress: "0x00...0000",
    status: "won",
    result: "50",
    ship_class: "ZEPHYR-7",
    current_score: "10",
    challenge_time: "12",
    bet_amount: "50.66",
  },
  {
    playerAddress: "0x00...0000",
    status: "won",
    result: "50",
    ship_class: "TITAN STEEL",
    current_score: "60",
    challenge_time: "48",
    bet_amount: "31.20",
  },
];
